version: "3.8"

services:

  taro:
    build:
      context: src
      dockerfile: src/Dockerfile
    container_name: taro-backend
    ports:
      - "8080:8080"
    env_file:
      - src/.env
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}


volumes:
  mysql-data: